export enum ENDPOINT_PATH {
	GET_AGENDA = '/data/agenda',
	GET_AGENDA_BY_ID = '/data/agenda/:id',
	GET_NEWS = '/data/news',
	GET_NEWS_BY_SLUG = '/data/news/:slug',
	GET_CITY_INDEX = '/issp/index',
	GET_SERVICE = '/issp/app',
	GET_SERVICE_CLUSTER = '/issp/cluster',
	GET_SERVICE_ORG = '/issp/dinas',
	GET_ORG_DETAILS = '/service-org',
	GET_SEARCH = '/search',
	GET_SERVICE_SEARCH = '/search/app',
	GET_SERVICE_SEARCH_HIGHLIGHT = '/search/app/highlight',
	GET_NEWS_SEARCH = '/search/news',
	GET_NEWS_SEARCH_HIGHLIGHT = '/search/news/highlight',
	GET_AGENDA_SEARCH = '/agenda/search',
	GET_AGENDA_SEARCH_HIGHLIGHT = '/agenda/searchHighlight',
	GET_CITY_INDEX_SEARCH = '/index/search',
	GET_CITY_INDEX_SEARCH_HIGHLIGHT = '/index/searchHighlight',
}
